#############################################Deployment groups##################

- id: backup
  type: group
  role: [backup]
  requires: [deploy_start]
  required_for: [deploy_end]
  tasks: [fuel_pkgs, hiera, globals, global-deploy-hiera-override-task, tools,
    logging, netconfig,  hosts, firewall]
  parameters:
    strategy:
      type: parallel


#############################################Tasks##############################

- id: global-deploy-hiera-override-task
  type: puppet
  groups: [controller, primary-controller, compute, base-os]
  requires: [globals]
  required_for: [logging]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/backup/manifests/deploy_hiera_override.pp
    puppet_modules: /etc/puppet/modules
    timeout: 120

- id: mysql-backup-task
  type: puppet
  groups: [primary-controller]
  requires: [database]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/backup/manifests/backup_mysql.pp
    puppet_modules: /etc/puppet/modules:/etc/puppet/modules/osnailyfacter/modular/backup/modules/
    timeout: 3600


