attributes:
  metadata:
    weight: 5
  backup_location:
    value: '/var/backups'
    label: 'Backup location'
    description: 'Please select location of Backups'
    weight: 20
    type: "text"
    restrictions:
      - action: hide
        condition: settings:backup.metadata.enabled == false
    weight: 30
  numtokeep:
    value: '7'
    label: 'Copies to keep'
    description: 'Number of copies to keep'
    weight: 20
    type: "text"
    restrictions:
      - action: hide
        condition: settings:backup.metadata.enabled == false
    weight: 30